[package]
name = "hyperchain-cli"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
libhyperchain = { path = "../lib" }
clap = "2.33.3"

