name: Rust

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: cd lib && cargo build --verbose &&
           cd service && cargo build --verbose &&
           cd cli && cargo build --verbose
    - name: Run tests
      run: cd lib && cargo test --verbose &&
           cd service && cargo test --verbose &&
           cd cli && cargo test --verbose
